name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  bumping:
    uses: LianJo/DevTestPublic/.github/workflows/trigger.yml@master
    secrets:
      CI_BOT_GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }}

  build:
    needs: bumping
    runs-on: ubuntu-20.04
  
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: test
        run: |
          foo=("aa" "bb")
          echo ${#foo[*]}

          echo ${{ needs.bumping }}
