name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  bumping:
    if: contains(github.ref, 'master') 
    uses: LianJo/DevTestPublic/.github/workflows/trigger.yml@master
    secrets:
      CI_BOT_GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }}

  test-build:
    runs-on: ubuntu-20.04
  
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: test
        run: |
          echo 'ti=aaaag' >> $GITHUB_OUTPUT
          
      - name: test2
        run: |
          echo "${{ steps.test.outputs.ti }}"
