name: CI

on:
  pull_request_review:
    types: [submitted]

  workflow_dispatch:

jobs:
  build:
    if: github.event.sender.login != "LianJo"
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      
