name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    if: github.event.ref == 'refs/heads/master' || github.event.sender.login != 'LianJo'
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: test
        run: |
          echo ${{ toJson(github.event) }}
