name: CI

on:
  pull_request_review:
    types: [submitted]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PARTNER_PAT }}
          MERGE_LABELS: ""
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 10000
          MERGE_METHOD: rebase
